name: CI/CD Pipeline updated

on:
  pull_request:
    types: [closed]
    branches:
      - main # trigger pipeline on push to main branch

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub
      run: echo "${{ secrets.Docker_Token }}" | docker login -u "${{ secrets.Docker_Username}}" --password-stdin

    - name: Build Docker image
      run: docker build -t "${{ secrets.Docker_Username}}"/fastapi-app:latest .

    - name: Push Docker image
      run: docker push "${{ secrets.Docker_Username}}"/fastapi-app:latest